$.fn.recurring_select.texts = {
  locale_iso_code: "de",
  repeat: "Wiederholen",
  last_day: "Letzter Tag",
  frequency: "Häufigkeit",
  daily: "Täglich",
  weekly: "Wöchentlich",
  monthly: "Monatlich",
  yearly: "Jährlich",
  every: "Alle",
  days: "Tag(e)",
  weeks_on: "Woche(n) am",
  months: "Monat(e)",
  years: "Jahr(e)",
  first_day_of_week: 1,
  day_of_month: "Tage des Monats",
  day_of_week: "Tage der Woche",
  cancel: "Abbrechen",
  ok: "Ok",
  summary: "Zusammenfassung",
  days_first_letter: ["S", "M", "D", "M", "D", "F", "S"],
  order: ["1.", "2.", "3.", "4.", "5.", "Letzter"]
}
