$.fn.recurring_select.texts = {
  locale_iso_code: "hu",
  repeat: "Ismétlés",
  last_day: 'Utolsó nap',
  frequency: "Gyakoriság",
  daily: "Naponta",
  weekly: "Hetente",
  monthly: "Havonta",
  yearly: "Évente",
  every: "Minden",
  days: ". napon",
  weeks_on: ". héten ekkor:",
  months: ". hónapban",
  years: ". évben",
  first_day_of_week: 1,
  day_of_month: "Hónap napján",
  day_of_week: "Hét napján",
  cancel: "Mégsem",
  ok: "OK",
  days_first_letter: ["V", "H", "K", "S", "C", "P", "S"],
  order: ["1.", "2.", "3.", "4.", "5.", "Utolsó"],
  summary: 'Összegzés',
  show_week: [true, true, true, true, false, false]
}
