name: test

on: [ push, pull_request ]

jobs:
  test:
    name: ${{matrix.ruby}}, ${{matrix.gemfile}}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.0', '3.1', '3.2', '3.3' ]
        gemfile:
          - Gemfile
          - spec/gemfiles/rails-6.1
          - spec/gemfiles/rails-7.0

    env:
      BUNDLE_GEMFILE: ${{matrix.gemfile}}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{matrix.ruby}}
          bundler-cache: true # 'bundle install' and cache
      - run: bundle exec rspec --format documentation
